---

- name: Cargar variables específicas del sistema
  ansible.builtin.include_vars: "redmine.yml"

- name: Instalar rvm y Ruby
  ansible.builtin.import_tasks: rvm-ruby.yml

- name: Instalar y configurar Redmine
  ansible.builtin.import_tasks: redmine.yml

- name: Habilitar y configurar el servicio de Redmine
  ansible.builtin.include_tasks: "systemd.yml"
  when: ansible_virtualization_type is defined and ansible_virtualization_type != "docker"

