---

- name: Instalar y configurar Redmine
  block:
    - name: Descargar Redmine
      ansible.builtin.get_url:
        url: "https://www.redmine.org/releases/redmine-{{ redmine_version }}.zip"
        dest: /tmp/redmine-{{ redmine_version }}.zip
        mode: 0777

    - name: Descomprimir Redmine
      ansible.builtin.unarchive:
        src: /tmp/redmine-{{ redmine_version }}.zip
        dest: /opt/
        remote_src: yes
        owner: "{{ ansible_env.USER }}"
        mode: 0755
      become: true
        

    - name: Copia Template de Configuración de DB
      ansible.builtin.template:
        src: database.yml.j2
        dest: /opt/redmine-{{ redmine_version }}/config/database.yml
        mode: 0644
        owner: "{{ ansible_env.USER }}"
      become: true

    - name: Copiar Template de Gemfile
      ansible.builtin.template:
        src: Gemfile.j2
        dest: /opt/redmine-{{ redmine_version }}/Gemfile
        mode: 0644
        owner: "{{ ansible_env.USER }}"
      become: true
    
    - name: Habilitar ruby en el directorio de redmine
      ansible.builtin.command: |
        asdf set ruby {{ ruby_version }}
      args:
        chdir: /opt/redmine-{{ redmine_version }}

    - name: Instalar gemas desde el Gemfile
      ansible.builtin.shell: |
        . "$HOME/.asdf/asdf.sh" && \
        gem install bundler && \
        bundle install
      args:
        executable: /bin/bash
        chdir: /opt/redmine-{{ redmine_version }}

    - name: Levantar redmine (db, migraciones y datos por defecto)
      ansible.builtin.shell: |
        . "$HOME/.asdf/asdf.sh" && \
        bundle exec rake generate_secret_token && \
        bundle exec rake db:migrate && \
        bundle exec rake redmine:load_default_data
      args:
        executable: /bin/bash
        chdir: /opt/redmine-{{ redmine_version }}

      
    - name: Levantar el servidor Puma
      ansible.builtin.shell: |
        . "$HOME/.asdf/asdf.sh" && RAILS_ENV=production bundle exec rails server
      args:
        executable: /bin/bash
        chdir: /opt/redmine-{{ redmine_version }}
