---

- name: Instalar y configurar Redmine
  block:
    - name: Descargar Redmine
      ansible.builtin.get_url:
        url: "https://www.redmine.org/releases/redmine-{{ redmine_version }}.zip"
        dest: /tmp/redmine-{{ redmine_version }}.zip
        mode: 0777

    - name: Descomprimir Redmine
      ansible.builtin.unarchive:
        src: /tmp/redmine-{{ redmine_version }}.zip
        dest: /opt/
        remote_src: yes
        owner: "{{ ansible_env.USER }}"
        mode: 0755
      become: true
        

    - name: Copia Template de Configuración de DB
      ansible.builtin.template:
        src: database.yml.j2
        dest: /opt/redmine-{{ redmine_version }}/config/database.yml
        mode: 0644
        owner: "{{ ansible_env.USER }}"
      become: true

    - name: Copiar Template de Gemfile
      ansible.builtin.template:
        src: Gemfile.j2
        dest: /opt/redmine-{{ redmine_version }}/Gemfile
        mode: 0644
        owner: "{{ ansible_env.USER }}"
      become: true
    

    - name: Instalar gemas desde el Gemfile
      ansible.builtin.shell: |
        export PATH="$HOME/.rbenv/bin:$PATH"
        eval "$(~/.rbenv/bin/rbenv init - bash)"
        gem install bundler
        bundle install
      args:
        executable: /bin/bash
        chdir: /opt/redmine-{{ redmine_version }}
      environment:


    - name: Levantar redmine (db, migraciones y datos por defecto)
      ansible.builtin.shell: |
        export PATH="$HOME/.rbenv/bin:$PATH"
        eval "$(~/.rbenv/bin/rbenv init - bash)"
        bundle exec rake generate_secret_token &&
        RAILS_ENV=production bundle exec rake db:migrate &&
        RAILS_ENV=production REDMINE_LANG=es bundle exec rake redmine:load_default_data
      args:
        executable: /bin/bash
        chdir: /opt/redmine-{{ redmine_version }}
