- name: Instalar y configurar Ruby con rbenv
  block:

    - name: Instalar dependencias para Ruby
      ansible.builtin.apt:
        name: '{{ rvm_dependencies }}'
        state: present
        update_cache: yes
      become: true

    - name: Clonar rbenv
      ansible.builtin.git:
        repo: 'https://github.com/rbenv/rbenv.git'
        dest: "{{ ansible_env.HOME }}/.rbenv"
        update: no

    - name: Clonar plugin ruby-build
      ansible.builtin.git:
        repo: 'https://github.com/rbenv/ruby-build.git'
        dest: "{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build"
        update: no

    - name: Agregar rbenv al PATH en .bashrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
        insertafter: EOF

    - name: Inicializar rbenv en .bashrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'eval "$(rbenv init - bash)"'
        insertafter: EOF

    - name: Instalar Ruby con rbenv
      ansible.builtin.shell: |
        export PATH="$HOME/.rbenv/bin:$PATH"
        eval "$(rbenv init - bash)"
        rbenv install -s {{ ruby_version }}
        rbenv global {{ ruby_version }}
        rbenv rehash
      args:
        executable: /bin/bash
      environment:
        HOME: "{{ ansible_env.HOME }}"
