---
galaxy_info:
  role_name: redmine           # debe ser en minúsculas, sin guiones al principio ni caracteres especiales
  namespace: cheo              # tu nombre de usuario en Galaxy, o algo válido
  author: cheo
  description: Redmine role for deploying with rbenv Ruby
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - jammy
